
import React, { useState, useRef, useCallback, useEffect } from 'react';
import JSZip from 'jszip';
import CodeIcon from './icons/CodeIcon';
import PlayIcon from './icons/PlayIcon';
import AIIcon from './icons/AIIcon';
import GamePreview from './GamePreview';
import ChatPanel from './ChatPanel';
import { Workspace } from '../types';
import RefreshIcon from './icons/RefreshIcon';
import FullscreenIcon from './icons/FullscreenIcon';
import DownloadIcon from './icons/DownloadIcon';
import SpinnerIcon from './icons/SpinnerIcon';
import PencilIcon from './icons/PencilIcon';
import ArrowLeftIcon from './icons/ArrowLeftIcon';


declare global {
    interface Window {
        hljs: any;
    }
}

interface IDEViewProps {
    activeWorkspace: Workspace;
    isLoading: boolean;
    onGenerate: (prompt: string) => void;
    onPositiveFeedback: (messageId: string) => void;
    onRetry: (prompt: string) => void;
    onRenameWorkspace: (newName: string) => void;
    onDeleteWorkspace: () => void;
    onReturnToLauncher: () => void;
}

const IDEView: React.FC<IDEViewProps> = ({ activeWorkspace, isLoading, onGenerate, onPositiveFeedback, onRetry, onRenameWorkspace, onDeleteWorkspace, onReturnToLauncher }) => {
    const [isChatVisible, setChatVisible] = useState(true);
    const [isPreviewVisible, setPreviewVisible] = useState(true);
    const [refreshKey, setRefreshKey] = useState(0);
    const previewContainerRef = useRef<HTMLDivElement>(null);
    const codeBlockRef = useRef<HTMLElement>(null);

    const [isEditingName, setIsEditingName] = useState(false);
    const [workspaceName, setWorkspaceName] = useState(activeWorkspace.name);
    const nameInputRef = useRef<HTMLInputElement>(null);

    useEffect(() => {
        if (codeBlockRef.current && window.hljs) {
            window.hljs.highlightElement(codeBlockRef.current);
        }
    }, [activeWorkspace.code]);
    
    useEffect(() => {
        if (isEditingName && nameInputRef.current) {
            nameInputRef.current.focus();
            nameInputRef.current.select();
        }
    }, [isEditingName]);

    const handleNameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        setWorkspaceName(e.target.value);
    }
    
    const handleNameBlur = () => {
        setIsEditingName(false);
        if (workspaceName.trim() && workspaceName !== activeWorkspace.name) {
            onRenameWorkspace(workspaceName);
        } else {
            setWorkspaceName(activeWorkspace.name); // revert if empty or unchanged
        }
    }
    
    const handleNameKeyDown = (e: React.KeyboardEvent) => {
        if (e.key === 'Enter') {
            e.currentTarget.blur();
        } else if (e.key === 'Escape') {
            setWorkspaceName(activeWorkspace.name);
            setIsEditingName(false);
        }
    }


    const handleRefresh = () => {
        setRefreshKey(prevKey => prevKey + 1);
    };

    const handleToggleFullscreen = useCallback(() => {
        if (!previewContainerRef.current) return;

        if (!document.fullscreenElement) {
            previewContainerRef.current.requestFullscreen().catch(err => {
                console.error(`Error attempting to enable full-screen mode: ${err.message} (${err.name})`);
            });
        } else {
            if (document.exitFullscreen) {
                document.exitFullscreen();
            }
        }
    }, []);

    const handleDownload = async () => {
        const zip = new JSZip();
        zip.file("index.html", activeWorkspace.code);

        const packageJson = {
            name: activeWorkspace.name.toLowerCase().replace(/\s+/g, '-'),
            version: "1.0.0",
            description: `A ${activeWorkspace.type} game generated by VibeCode-X AI.`,
            scripts: { "start": "serve ." },
            devDependencies: { "serve": "^14.2.1" }
        };
        zip.file("package.json", JSON.stringify(packageJson, null, 2));

        const vercelJson = { "rewrites": [{ "source": "/(.*)", "destination": "/index.html" }] };
        zip.file("vercel.json", JSON.stringify(vercelJson, null, 2));
        
        const readmeContent = `# ${activeWorkspace.name}\n\nThis project was generated using VibeCode-X AI.\n\n## Local Development\n\n1.  Ensure Node.js and npm are installed.\n2.  Install dependencies: \`npm install\`\n3.  Start the server: \`npm start\`\n`;
        zip.file("README.md", readmeContent);

        const blob = await zip.generateAsync({ type: "blob" });
        const link = document.createElement("a");
        link.href = URL.createObjectURL(blob);
        link.download = `${activeWorkspace.name.toLowerCase().replace(/\s+/g, '-')}.zip`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    };


    return (
        <div className="relative flex h-screen w-screen bg-black text-gray-300 font-sans">
             <div className={`bg-[#121212] flex flex-col flex-shrink-0 border-r border-gray-800/70 transition-all duration-300 ease-in-out ${isChatVisible ? 'w-[380px]' : 'w-0'}`}>
                {isChatVisible && <ChatPanel history={activeWorkspace.chatHistory} onSend={onGenerate} isLoading={isLoading} onDeleteWorkspace={onDeleteWorkspace} onPositiveFeedback={onPositiveFeedback} onRetry={onRetry} />}
            </div>
            
            <div className="flex-1 flex flex-col overflow-hidden">
                <header className="flex-shrink-0 bg-[#121212] border-b border-gray-800/70 flex justify-between items-center px-2 h-11">
                     <div className="flex items-center gap-1">
                        <button
                            onClick={onReturnToLauncher}
                            className="p-1.5 text-gray-400 rounded-md hover:text-white hover:bg-white/10 transition-colors"
                            aria-label="Back to Launcher"
                        >
                            <ArrowLeftIcon className="w-5 h-5" />
                        </button>
                        <button
                            onClick={() => setChatVisible(!isChatVisible)}
                            className="p-1.5 text-gray-400 rounded-md hover:text-white hover:bg-white/10 transition-colors"
                            aria-label={isChatVisible ? 'Hide Chat Panel' : 'Show Chat Panel'}
                        >
                            <AIIcon className={`w-5 h-5 transition-colors ${isChatVisible ? 'text-blue-500' : 'text-gray-400'}`} />
                        </button>
                        <div className="h-5 w-px bg-gray-800 mx-1"></div>
                        <div className="flex items-center gap-3">
                             {isEditingName ? (
                                <input
                                    ref={nameInputRef}
                                    type="text"
                                    value={workspaceName}
                                    onChange={handleNameChange}
                                    onBlur={handleNameBlur}
                                    onKeyDown={handleNameKeyDown}
                                    className="bg-black border border-blue-500 rounded-md px-2 py-0.5 text-sm font-medium text-gray-200 outline-none w-48"
                                />
                            ) : (
                                <div onClick={() => setIsEditingName(true)} className="group flex items-center gap-2 px-2 py-1.5 text-sm font-medium bg-black rounded-md border border-transparent hover:border-gray-700/80 cursor-pointer" title="Double-click to rename">
                                    <CodeIcon className="w-4 h-4 text-gray-500" />
                                    <span className="text-gray-300">{activeWorkspace.name}</span>
                                    <PencilIcon className="w-3 h-3 text-gray-600 ml-1 opacity-0 group-hover:opacity-100 transition-opacity" />
                                </div>
                            )}
                            <span className="text-xs font-semibold uppercase text-blue-400 bg-blue-500/10 px-2 py-1 rounded-full">{activeWorkspace.type}</span>
                        </div>
                     </div>
                    <div className="flex items-center gap-1">
                        <button
                            onClick={handleDownload}
                            className="p-1.5 text-gray-400 rounded-md hover:text-white hover:bg-white/10 transition-colors"
                            aria-label="Download Project"
                        >
                           <DownloadIcon className="w-5 h-5" />
                        </button>
                         <button
                            onClick={handleRefresh}
                            className="p-1.5 text-gray-400 rounded-md hover:text-white hover:bg-white/10 transition-colors"
                            aria-label="Refresh Preview"
                        >
                           <RefreshIcon className="w-5 h-5" />
                        </button>
                        <button
                            onClick={handleToggleFullscreen}
                            className="p-1.5 text-gray-400 rounded-md hover:text-white hover:bg-white/10 transition-colors"
                            aria-label="Toggle Fullscreen"
                        >
                           <FullscreenIcon className="w-5 h-5" />
                        </button>
                         <button
                            onClick={() => setPreviewVisible(!isPreviewVisible)}
                            className="p-1.5 text-gray-400 rounded-md hover:text-white hover:bg-white/10 transition-colors"
                            aria-label={isPreviewVisible ? 'Hide Preview' : 'Show Preview'}
                        >
                            <PlayIcon className={`w-5 h-5 transition-colors ${isPreviewVisible ? 'text-blue-500' : 'text-gray-400'}`} />
                        </button>
                    </div>
                </header>

                <main className="flex-1 bg-black flex flex-row overflow-hidden">
                    <div className={`h-full overflow-auto transition-all duration-300 ease-in-out font-mono text-sm bg-black ${isPreviewVisible ? 'w-1/2 border-r border-gray-800/70' : 'w-full'}`}>
                         <div className="p-4 h-full">
                            <pre className="h-full w-full"><code ref={codeBlockRef} className="language-html">{activeWorkspace.code}</code></pre>
                        </div>
                    </div>

                    <div ref={previewContainerRef} className={`relative h-full bg-black transition-all duration-300 ease-in-out ${isPreviewVisible ? 'w-1/2' : 'w-0'}`}>
                        {isPreviewVisible && (
                           <GamePreview key={refreshKey} htmlContent={activeWorkspace.code} />
                        )}
                    </div>
                </main>
            </div>

            {isLoading && (
                <div className="absolute bottom-5 left-1/2 -translate-x-1/2 bg-gray-900/80 backdrop-blur-sm border border-white/10 text-gray-200 px-4 py-2 rounded-full flex items-center gap-3 shadow-lg z-50 transition-opacity duration-300 animate-fade-in">
                    <SpinnerIcon className="w-5 h-5 text-blue-400" />
                    <span>AI is thinking...</span>
                </div>
            )}
        </div>
    );
};

export default IDEView;
